# @format

apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: deploy-template
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${APP_NAME}-api
      namespace: ${NAMESPACE}
      labels:
        app: ${APP_NAME}-api
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ${APP_NAME}-api
          deployment: ${APP_NAME}-api
      template:
        metadata:
          labels:
            app: ${APP_NAME}-api
            deployment: ${APP_NAME}-api
            role: frontend
        spec:
          containers:
            - name: ${APP_NAME}-api
              image: ghcr.io/bcgov/${APP_NAME}-api:${TAG}
              ports:
                containerPort: 3333
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-api
      namespace: ${NAMESPACE}
      labels:
        app: ${APP_NAME}-api
    spec:
      ports:
        - name: 3333-tcp
          protocol: TCP
          port: 3333
          targetPort: 3333
      selector:
        app: ${APP_NAME}-api
        deployment: ${APP_NAME}-api
        role: frontend
      type: ClusterIP
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: ${APP_NAME}-api
      namespace: ${NAMESPACE}
      labels:
        app: ${APP_NAME}-api
    spec:
      host: ${APP_NAME}-${NAMESPACE}.apps.silver.devops.gov.bc.ca
      path: /api
      to:
        kind: Service
        name: ${APP_NAME}-api
        weight: 100
      port:
        targetPort: 3333-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
parameters:
  - name: APP_NAME
    displayName: Application Name
    required: true
  - name: NAMESPACE
    displayName: Namespace
    required: true
  - name: TAG
    displayName: Tag for github container registry
    required: false
    value: latest
  - name: PORT
    displayName: exposed port
    required: true
